CREATE TABLE RAID (
  ID CHARACTER VARYING(50) PRIMARY KEY,
  METAL BIGINT NOT NULL,
  CRYSTAL BIGINT NOT NULL,
  DEUTERIUM  BIGINT NOT NULL,
  TIMESTAMP VARCHAR NOT NULL,
  PLAYER_NAME VARCHAR NOT NULL
);